version: '3'
services: 
  database:
    image: postgres:10-alpine
    restart: always
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=secret_password
      - POSTGRES_USER=hyperxpizza
      - POSTGRES_DB=vueqgltodo
    volumes: 
      - database-data:/var/lib/postgresql/data/
    networks: 
      - default
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    env_file: 
      - database.env
    depends_on: 
      - database
    networks: 
      - default
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on: 
      - server
    ports:
      - "8080:8080"
volumes:
  database-data: